### ISSUE TITLE
모바일에서 화면 깨짐 현상

### ISSUE THREAD

**Issue by songunnie** [BreedingMe/CoCoFrontend#121]

**Comment by serijang** [comment]
- 프로필 포트폴리오, 자기소개 영역에 스크롤이 생김 (모바일) → 한 눈에 보이도록 변경
- 모바일 버전에서 오른쪽 상단에 메뉴토글과 겹치지 않도록 margin-top 부여 (게시글 상세, 쪽지 목록)
